//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.18.0
//     from Assets/Input System Stuff/PlayerOne.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Input System Stuff/PlayerOne.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @PlayerOne: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @PlayerOne()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""PlayerOne"",
    ""maps"": [
        {
            ""name"": ""Player one"",
            ""id"": ""c91e694b-6b80-45dc-9f78-4324e35ccd4a"",
            ""actions"": [
                {
                    ""name"": ""Fire"",
                    ""type"": ""Button"",
                    ""id"": ""cba3b6f9-3a0a-4e65-a6da-db7800f58e38"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Top Circle"",
                    ""type"": ""Button"",
                    ""id"": ""aaf274d6-d9eb-4379-821e-889558f8e68a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Top Square"",
                    ""type"": ""Button"",
                    ""id"": ""919e21e2-7b26-4522-b97f-7f94e6ceada7"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Bottom Circle"",
                    ""type"": ""Button"",
                    ""id"": ""db61e7fe-815a-43bf-bd8c-956e534a548a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Bottom Square"",
                    ""type"": ""Button"",
                    ""id"": ""c081226d-521d-44f7-ad74-d9f506b2e650"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Bottom Triangle"",
                    ""type"": ""Button"",
                    ""id"": ""8a305bbe-0822-467f-80ea-f64fac1422e9"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""e16b78d1-53c9-4a65-8b1b-20556e584f01"",
                    ""path"": ""<Keyboard>/rightShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Fire"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""37735dff-6db4-44d3-b758-ee035c5f2576"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Fire"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b0d3cae7-301a-4887-ab3a-ec3d8996440e"",
                    ""path"": ""<Keyboard>/o"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Top Circle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""888cd70d-2b48-451d-92c2-bfbadb66160c"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Top Circle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e57cb1df-294d-45f1-a9e4-2ea5551ea3e8"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Top Square"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""093ff69f-c0b6-445e-b98e-3214f63862e1"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Top Square"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""02e8985f-a152-436c-bf31-a6d8cc4b7c39"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Bottom Circle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8e14baca-606c-4452-b36f-682e1be6854d"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Bottom Circle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""791fcac5-04cc-4fe4-8a41-7d25f83b6dcb"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Bottom Square"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""731d3741-7a9d-454e-9427-4b2294dab9bc"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Bottom Square"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d9959304-d06c-4764-8557-43d68bfc7935"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Bottom Triangle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a5db54aa-c977-4842-a46f-2a3f83ce54d6"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Bottom Triangle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Player two"",
            ""id"": ""b1210841-4652-42b0-8eb5-7a5ff1ffbc98"",
            ""actions"": [
                {
                    ""name"": ""Fire"",
                    ""type"": ""Button"",
                    ""id"": ""300fded3-7402-4047-b65e-1bb586a51d18"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Top Triangle"",
                    ""type"": ""Button"",
                    ""id"": ""2a370a6b-a388-4d56-8436-b991572277b5"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Top Square"",
                    ""type"": ""Button"",
                    ""id"": ""c8878793-3acc-47c6-bfd2-cf397e195627"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Bottom Circle"",
                    ""type"": ""Button"",
                    ""id"": ""46938d75-af7f-4b6a-b568-5eb67a8ced5e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Bottom Square"",
                    ""type"": ""Button"",
                    ""id"": ""0cc65dad-c8e9-4bfa-ba99-cb40814c6a32"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Bottom Triangle"",
                    ""type"": ""Button"",
                    ""id"": ""c1449e4f-89c4-4803-aac7-2958ee480e89"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""a891f56d-89ca-4850-9adb-26acdc3eaca2"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Fire"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""489ee873-c91c-4554-be3d-ada246c8a028"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Fire"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6d0bc058-2e84-48c2-addc-d457c37a1de7"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Top Triangle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""201c02bc-2b8e-440d-9a12-92dfda29faee"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Top Triangle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2c485659-3a76-4fbf-8a35-b446c73e9cd4"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Top Square"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fe1a56f0-8a5f-4d25-8fce-2ae0c5e4a803"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Top Square"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c6d8ffa1-c74e-405b-a1d2-c98efa9fa344"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Bottom Circle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""153a0c33-1259-4249-9d02-b7f218ce2d87"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Bottom Circle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""923133f3-8ae9-4d60-9580-2de96a63f272"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Bottom Square"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e283213a-2c53-42db-8a6f-dd765a282e10"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Bottom Square"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""76d3d55a-9e7c-42ae-bf1e-382fa3d586c8"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Bottom Triangle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ce2f3eee-1bbe-457b-9b6e-f2b667c4957a"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Bottom Triangle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Controller scheme"",
            ""bindingGroup"": ""Controller scheme"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Player one
        m_Playerone = asset.FindActionMap("Player one", throwIfNotFound: true);
        m_Playerone_Fire = m_Playerone.FindAction("Fire", throwIfNotFound: true);
        m_Playerone_TopCircle = m_Playerone.FindAction("Top Circle", throwIfNotFound: true);
        m_Playerone_TopSquare = m_Playerone.FindAction("Top Square", throwIfNotFound: true);
        m_Playerone_BottomCircle = m_Playerone.FindAction("Bottom Circle", throwIfNotFound: true);
        m_Playerone_BottomSquare = m_Playerone.FindAction("Bottom Square", throwIfNotFound: true);
        m_Playerone_BottomTriangle = m_Playerone.FindAction("Bottom Triangle", throwIfNotFound: true);
        // Player two
        m_Playertwo = asset.FindActionMap("Player two", throwIfNotFound: true);
        m_Playertwo_Fire = m_Playertwo.FindAction("Fire", throwIfNotFound: true);
        m_Playertwo_TopTriangle = m_Playertwo.FindAction("Top Triangle", throwIfNotFound: true);
        m_Playertwo_TopSquare = m_Playertwo.FindAction("Top Square", throwIfNotFound: true);
        m_Playertwo_BottomCircle = m_Playertwo.FindAction("Bottom Circle", throwIfNotFound: true);
        m_Playertwo_BottomSquare = m_Playertwo.FindAction("Bottom Square", throwIfNotFound: true);
        m_Playertwo_BottomTriangle = m_Playertwo.FindAction("Bottom Triangle", throwIfNotFound: true);
    }

    ~@PlayerOne()
    {
        UnityEngine.Debug.Assert(!m_Playerone.enabled, "This will cause a leak and performance issues, PlayerOne.Playerone.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_Playertwo.enabled, "This will cause a leak and performance issues, PlayerOne.Playertwo.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player one
    private readonly InputActionMap m_Playerone;
    private List<IPlayeroneActions> m_PlayeroneActionsCallbackInterfaces = new List<IPlayeroneActions>();
    private readonly InputAction m_Playerone_Fire;
    private readonly InputAction m_Playerone_TopCircle;
    private readonly InputAction m_Playerone_TopSquare;
    private readonly InputAction m_Playerone_BottomCircle;
    private readonly InputAction m_Playerone_BottomSquare;
    private readonly InputAction m_Playerone_BottomTriangle;
    /// <summary>
    /// Provides access to input actions defined in input action map "Player one".
    /// </summary>
    public struct PlayeroneActions
    {
        private @PlayerOne m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public PlayeroneActions(@PlayerOne wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "Playerone/Fire".
        /// </summary>
        public InputAction @Fire => m_Wrapper.m_Playerone_Fire;
        /// <summary>
        /// Provides access to the underlying input action "Playerone/TopCircle".
        /// </summary>
        public InputAction @TopCircle => m_Wrapper.m_Playerone_TopCircle;
        /// <summary>
        /// Provides access to the underlying input action "Playerone/TopSquare".
        /// </summary>
        public InputAction @TopSquare => m_Wrapper.m_Playerone_TopSquare;
        /// <summary>
        /// Provides access to the underlying input action "Playerone/BottomCircle".
        /// </summary>
        public InputAction @BottomCircle => m_Wrapper.m_Playerone_BottomCircle;
        /// <summary>
        /// Provides access to the underlying input action "Playerone/BottomSquare".
        /// </summary>
        public InputAction @BottomSquare => m_Wrapper.m_Playerone_BottomSquare;
        /// <summary>
        /// Provides access to the underlying input action "Playerone/BottomTriangle".
        /// </summary>
        public InputAction @BottomTriangle => m_Wrapper.m_Playerone_BottomTriangle;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_Playerone; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="PlayeroneActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(PlayeroneActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="PlayeroneActions" />
        public void AddCallbacks(IPlayeroneActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayeroneActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayeroneActionsCallbackInterfaces.Add(instance);
            @Fire.started += instance.OnFire;
            @Fire.performed += instance.OnFire;
            @Fire.canceled += instance.OnFire;
            @TopCircle.started += instance.OnTopCircle;
            @TopCircle.performed += instance.OnTopCircle;
            @TopCircle.canceled += instance.OnTopCircle;
            @TopSquare.started += instance.OnTopSquare;
            @TopSquare.performed += instance.OnTopSquare;
            @TopSquare.canceled += instance.OnTopSquare;
            @BottomCircle.started += instance.OnBottomCircle;
            @BottomCircle.performed += instance.OnBottomCircle;
            @BottomCircle.canceled += instance.OnBottomCircle;
            @BottomSquare.started += instance.OnBottomSquare;
            @BottomSquare.performed += instance.OnBottomSquare;
            @BottomSquare.canceled += instance.OnBottomSquare;
            @BottomTriangle.started += instance.OnBottomTriangle;
            @BottomTriangle.performed += instance.OnBottomTriangle;
            @BottomTriangle.canceled += instance.OnBottomTriangle;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="PlayeroneActions" />
        private void UnregisterCallbacks(IPlayeroneActions instance)
        {
            @Fire.started -= instance.OnFire;
            @Fire.performed -= instance.OnFire;
            @Fire.canceled -= instance.OnFire;
            @TopCircle.started -= instance.OnTopCircle;
            @TopCircle.performed -= instance.OnTopCircle;
            @TopCircle.canceled -= instance.OnTopCircle;
            @TopSquare.started -= instance.OnTopSquare;
            @TopSquare.performed -= instance.OnTopSquare;
            @TopSquare.canceled -= instance.OnTopSquare;
            @BottomCircle.started -= instance.OnBottomCircle;
            @BottomCircle.performed -= instance.OnBottomCircle;
            @BottomCircle.canceled -= instance.OnBottomCircle;
            @BottomSquare.started -= instance.OnBottomSquare;
            @BottomSquare.performed -= instance.OnBottomSquare;
            @BottomSquare.canceled -= instance.OnBottomSquare;
            @BottomTriangle.started -= instance.OnBottomTriangle;
            @BottomTriangle.performed -= instance.OnBottomTriangle;
            @BottomTriangle.canceled -= instance.OnBottomTriangle;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="PlayeroneActions.UnregisterCallbacks(IPlayeroneActions)" />.
        /// </summary>
        /// <seealso cref="PlayeroneActions.UnregisterCallbacks(IPlayeroneActions)" />
        public void RemoveCallbacks(IPlayeroneActions instance)
        {
            if (m_Wrapper.m_PlayeroneActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="PlayeroneActions.AddCallbacks(IPlayeroneActions)" />
        /// <seealso cref="PlayeroneActions.RemoveCallbacks(IPlayeroneActions)" />
        /// <seealso cref="PlayeroneActions.UnregisterCallbacks(IPlayeroneActions)" />
        public void SetCallbacks(IPlayeroneActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayeroneActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayeroneActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="PlayeroneActions" /> instance referencing this action map.
    /// </summary>
    public PlayeroneActions @Playerone => new PlayeroneActions(this);

    // Player two
    private readonly InputActionMap m_Playertwo;
    private List<IPlayertwoActions> m_PlayertwoActionsCallbackInterfaces = new List<IPlayertwoActions>();
    private readonly InputAction m_Playertwo_Fire;
    private readonly InputAction m_Playertwo_TopTriangle;
    private readonly InputAction m_Playertwo_TopSquare;
    private readonly InputAction m_Playertwo_BottomCircle;
    private readonly InputAction m_Playertwo_BottomSquare;
    private readonly InputAction m_Playertwo_BottomTriangle;
    /// <summary>
    /// Provides access to input actions defined in input action map "Player two".
    /// </summary>
    public struct PlayertwoActions
    {
        private @PlayerOne m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public PlayertwoActions(@PlayerOne wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "Playertwo/Fire".
        /// </summary>
        public InputAction @Fire => m_Wrapper.m_Playertwo_Fire;
        /// <summary>
        /// Provides access to the underlying input action "Playertwo/TopTriangle".
        /// </summary>
        public InputAction @TopTriangle => m_Wrapper.m_Playertwo_TopTriangle;
        /// <summary>
        /// Provides access to the underlying input action "Playertwo/TopSquare".
        /// </summary>
        public InputAction @TopSquare => m_Wrapper.m_Playertwo_TopSquare;
        /// <summary>
        /// Provides access to the underlying input action "Playertwo/BottomCircle".
        /// </summary>
        public InputAction @BottomCircle => m_Wrapper.m_Playertwo_BottomCircle;
        /// <summary>
        /// Provides access to the underlying input action "Playertwo/BottomSquare".
        /// </summary>
        public InputAction @BottomSquare => m_Wrapper.m_Playertwo_BottomSquare;
        /// <summary>
        /// Provides access to the underlying input action "Playertwo/BottomTriangle".
        /// </summary>
        public InputAction @BottomTriangle => m_Wrapper.m_Playertwo_BottomTriangle;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_Playertwo; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="PlayertwoActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(PlayertwoActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="PlayertwoActions" />
        public void AddCallbacks(IPlayertwoActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayertwoActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayertwoActionsCallbackInterfaces.Add(instance);
            @Fire.started += instance.OnFire;
            @Fire.performed += instance.OnFire;
            @Fire.canceled += instance.OnFire;
            @TopTriangle.started += instance.OnTopTriangle;
            @TopTriangle.performed += instance.OnTopTriangle;
            @TopTriangle.canceled += instance.OnTopTriangle;
            @TopSquare.started += instance.OnTopSquare;
            @TopSquare.performed += instance.OnTopSquare;
            @TopSquare.canceled += instance.OnTopSquare;
            @BottomCircle.started += instance.OnBottomCircle;
            @BottomCircle.performed += instance.OnBottomCircle;
            @BottomCircle.canceled += instance.OnBottomCircle;
            @BottomSquare.started += instance.OnBottomSquare;
            @BottomSquare.performed += instance.OnBottomSquare;
            @BottomSquare.canceled += instance.OnBottomSquare;
            @BottomTriangle.started += instance.OnBottomTriangle;
            @BottomTriangle.performed += instance.OnBottomTriangle;
            @BottomTriangle.canceled += instance.OnBottomTriangle;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="PlayertwoActions" />
        private void UnregisterCallbacks(IPlayertwoActions instance)
        {
            @Fire.started -= instance.OnFire;
            @Fire.performed -= instance.OnFire;
            @Fire.canceled -= instance.OnFire;
            @TopTriangle.started -= instance.OnTopTriangle;
            @TopTriangle.performed -= instance.OnTopTriangle;
            @TopTriangle.canceled -= instance.OnTopTriangle;
            @TopSquare.started -= instance.OnTopSquare;
            @TopSquare.performed -= instance.OnTopSquare;
            @TopSquare.canceled -= instance.OnTopSquare;
            @BottomCircle.started -= instance.OnBottomCircle;
            @BottomCircle.performed -= instance.OnBottomCircle;
            @BottomCircle.canceled -= instance.OnBottomCircle;
            @BottomSquare.started -= instance.OnBottomSquare;
            @BottomSquare.performed -= instance.OnBottomSquare;
            @BottomSquare.canceled -= instance.OnBottomSquare;
            @BottomTriangle.started -= instance.OnBottomTriangle;
            @BottomTriangle.performed -= instance.OnBottomTriangle;
            @BottomTriangle.canceled -= instance.OnBottomTriangle;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="PlayertwoActions.UnregisterCallbacks(IPlayertwoActions)" />.
        /// </summary>
        /// <seealso cref="PlayertwoActions.UnregisterCallbacks(IPlayertwoActions)" />
        public void RemoveCallbacks(IPlayertwoActions instance)
        {
            if (m_Wrapper.m_PlayertwoActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="PlayertwoActions.AddCallbacks(IPlayertwoActions)" />
        /// <seealso cref="PlayertwoActions.RemoveCallbacks(IPlayertwoActions)" />
        /// <seealso cref="PlayertwoActions.UnregisterCallbacks(IPlayertwoActions)" />
        public void SetCallbacks(IPlayertwoActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayertwoActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayertwoActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="PlayertwoActions" /> instance referencing this action map.
    /// </summary>
    public PlayertwoActions @Playertwo => new PlayertwoActions(this);
    private int m_ControllerschemeSchemeIndex = -1;
    /// <summary>
    /// Provides access to the input control scheme.
    /// </summary>
    /// <seealso cref="UnityEngine.InputSystem.InputControlScheme" />
    public InputControlScheme ControllerschemeScheme
    {
        get
        {
            if (m_ControllerschemeSchemeIndex == -1) m_ControllerschemeSchemeIndex = asset.FindControlSchemeIndex("Controller scheme");
            return asset.controlSchemes[m_ControllerschemeSchemeIndex];
        }
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Player one" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="PlayeroneActions.AddCallbacks(IPlayeroneActions)" />
    /// <seealso cref="PlayeroneActions.RemoveCallbacks(IPlayeroneActions)" />
    public interface IPlayeroneActions
    {
        /// <summary>
        /// Method invoked when associated input action "Fire" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnFire(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Top Circle" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTopCircle(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Top Square" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTopSquare(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Bottom Circle" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnBottomCircle(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Bottom Square" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnBottomSquare(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Bottom Triangle" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnBottomTriangle(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Player two" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="PlayertwoActions.AddCallbacks(IPlayertwoActions)" />
    /// <seealso cref="PlayertwoActions.RemoveCallbacks(IPlayertwoActions)" />
    public interface IPlayertwoActions
    {
        /// <summary>
        /// Method invoked when associated input action "Fire" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnFire(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Top Triangle" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTopTriangle(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Top Square" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTopSquare(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Bottom Circle" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnBottomCircle(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Bottom Square" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnBottomSquare(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Bottom Triangle" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnBottomTriangle(InputAction.CallbackContext context);
    }
}
